### ISSUE TITLE
Air Purifier 400S - LAP-C401S-WUSR not showing up in the integration

### ISSUE THREAD

**Issue by adityapavan18** [vlebourl/custom_vesync#15]
Air Purifier 400S - LAP-C401S-WUSR not showing up in the integration. It does show up with pyvesync 2.0.0 but for some reason its not showing up in the HA integration. I have a humidifier 600s which shows up fine here, but not the air purifier

**Comment by vlebourl** [comment]
Hi, 
Thanks for the issue. Unfortunately, I don't own that device, so supporting it is quite hard... 
Is it already supported by the core integration? 
Cheers

**Comment by adityapavan18** [comment]
It wasn't showing up in core integration too. But it should be. I can access the device and control it via pyvesync though since 2.0.0. Because this custom component is using 2.0.1 - I thought it would show up as well. But it's not.

Also in logs this come up
This error originated from a custom integration.

Logger: custom_components.vesync.fan
Source: custom_components/vesync/fan.py:62 
Integration: VeSync 
First occurred: April 6, 2022, 10:28:51 PM (4 occurrences) 
Last logged: 11:44:48 AM

Air Purifier - Unknown device type - LAP-C401S-WUSR
Humidifier - Unknown device type - LUH-A602S-WUS

but humidifier shows up any way but not air purifier

After upgrading to latest code I just get this now

Logger: custom_components.vesync.fan
Source: custom_components/vesync/fan.py:62 
Integration: VeSync 
First occurred: 12:38:36 PM (1 occurrences) 
Last logged: 12:38:36 PM

Air Purifier - Unknown device type - LAP-C401S-WUSR

**Comment by borpin** [comment]
@vlebourl - the reason is the way the `is_humidifier` is implemented. This was a change I suggested on the original PR, so the list of models was searched for to match the humidifer not just the different 'classes' of humidifier.

The same modification to the model check needs to be done for the air purifiers.

https://github.com/vlebourl/custom_vesync/blob/35370cbcaed72a5cbd67b709562da1f52dbac664/custom_components/vesync/common.py#L21-L24

[edit]
BTW, This was my check - not sure if it is 'good' Python 🙍‍♂️ 

[edit2]
This has a knock on to the preset modes as well I think.

https://github.com/vlebourl/custom_vesync/blob/35370cbcaed72a5cbd67b709562da1f52dbac664/custom_components/vesync/fan.py#L24

**Comment by vlebourl** [comment]
Issue grouped with https://github.com/vlebourl/custom_vesync/issues/16 and https://github.com/vlebourl/custom_vesync/issues/18 in https://github.com/vlebourl/custom_vesync/issues/19.

**Comment by vlebourl** [comment]
is this still an issue?

**Comment by adityapavan18** [comment]
We can close this
