### ISSUE TITLE
Request to migrate this to Home Assistant repo

### ISSUE THREAD

**Issue by gquerbes** [vlebourl/custom_vesync#65]
Hello,
I recently starting adding support for the Classic 300S, and I realized you have already done so. I have been testing your code on my Home Assistant installation since yesterday and so far so good.

Do you have any plans to migrate this into the Home Assistant project so it's part of the native install?

Thank you!

**Comment by vlebourl** [comment]
Hi, 

Honestly, no... Moving stuff into HA core is a lot of work because they require a very high coding quality (and rightfuly so). Although I can make some time to keep this custom comp up to date and fix bugs and simple feature request, I don't have the time to make it mergeable into core... But if you do and want to take the migration into your own hands, please feel free to use whatever you need from this repo! 

Cheers
