### ISSUE TITLE
Add support for ...LEVOIT Smart Thermostat

### ISSUE THREAD

**Issue by Sledneck54** [vlebourl/custom_vesync#78]
### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Found the following devices:".
```

</details>

### Additional information

Im wondering if anyone is working on support for the "kinda" new Levoit Smart Thermostat that uses the VeSync app. I did some digging and couldn't find device support for this product for Home Assistant.

**Comment by vlebourl** [comment]
Hi,
Not that I know of... I don't own the device, so adding support is not an easy task.
Do you own it?

**Comment by Sledneck54** [comment]
No, I was thinking of purchasing one. According to amazon it's new for 2022. Full of the features I'm looking for. 
I won't purchase it if there's no Home Assistant support. 
I want to learn Python to help with device support. Any recommendations where to start?

**Comment by vlebourl** [comment]
I can't promise support without access to the device unfortunately, but I'm sure we can get it working. Home Assistant may not be the easiest way to stay Python if you do not have any prior experience in programming. Otherwise, a good way to start is to look at another integration, even a simple one like generic_thermostat and try to copy it.
